# Generated by Django 6.0.2 on 2026-02-21 08:04

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('cases', '0003_alter_case_options_alter_casemember_options_and_more'),
        ('evidence', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CustodyLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action_type', models.CharField(choices=[('UPLOAD', 'Evidence Uploaded'), ('VIEW', 'Evidence Viewed'), ('VERIFY', 'Evidence Verified'), ('DOWNLOAD', 'Evidence Downloaded'), ('INVESTIGATOR_ASSIGNED', 'Investigator Assigned'), ('CASE_UPDATE', 'Case Updated'), ('CLOSURE_REQUEST', 'Case Closure Requested'), ('CASE_CLOSED', 'Case Closed')], max_length=50)),
                ('remarks', models.TextField(blank=True, null=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('case', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='custody_logs', to='cases.case')),
                ('evidence', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='custody_logs', to='evidence.evidence')),
                ('performed_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['timestamp'],
            },
        ),
    ]
