# Generated by Django 6.0.2 on 2026-03-05 13:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('custody', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='custodylog',
            name='action_type',
            field=models.CharField(choices=[('UPLOAD', 'Evidence Uploaded'), ('PREVIEW', 'Evidence Previewed'), ('COMMENT', 'Evidence Commented'), ('VIEW', 'Evidence Viewed'), ('VERIFY', 'Evidence Verified'), ('DOWNLOAD', 'Evidence Downloaded'), ('INVESTIGATOR_ASSIGNED', 'Investigator Assigned'), ('CASE_UPDATE', 'Case Updated'), ('CLOSURE_REQUEST', 'Case Closure Requested'), ('CASE_CLOSED', 'Case Closed')], max_length=50),
        ),
    ]
