# Generated by Django 6.0.2 on 2026-02-14 13:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cases', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='casemember',
            name='role_in_case',
        ),
    ]
