# Generated by Django 6.0.2 on 2026-02-14 16:31

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cases', '0002_remove_casemember_role_in_case'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='case',
            options={'ordering': ['-created_at'], 'verbose_name': 'Case', 'verbose_name_plural': 'Cases'},
        ),
        migrations.AlterModelOptions(
            name='casemember',
            options={'ordering': ['-assigned_at'], 'verbose_name': 'Case Member', 'verbose_name_plural': 'Case Members'},
        ),
        migrations.AddField(
            model_name='case',
            name='category_other',
            field=models.CharField(blank=True, default='', help_text="Describe the category if 'Other' is selected", max_length=200),
        ),
        migrations.AddField(
            model_name='case',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='case',
            name='assigned_so',
            field=models.ForeignKey(help_text='Senior Officer assigned to this case', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_cases', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='case',
            name='case_id',
            field=models.CharField(help_text='Unique identifier for this case (e.g. CASE-2026-0001)', max_length=50, unique=True),
        ),
        migrations.AlterField(
            model_name='case',
            name='category',
            field=models.CharField(choices=[('CYBER_CRIME', 'Cyber Crime'), ('FRAUD', 'Fraud'), ('THEFT', 'Theft'), ('HOMICIDE', 'Homicide'), ('NARCOTICS', 'Narcotics'), ('ASSAULT', 'Assault'), ('MISSING_PERSON', 'Missing Person'), ('OTHER', 'Other')], help_text='Category of the case', max_length=50),
        ),
        migrations.AlterField(
            model_name='case',
            name='created_by',
            field=models.ForeignKey(help_text='Admin who created this case', on_delete=django.db.models.deletion.CASCADE, related_name='created_cases', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='case',
            name='description',
            field=models.TextField(help_text='Detailed description of the case'),
        ),
        migrations.AlterField(
            model_name='case',
            name='priority',
            field=models.CharField(choices=[('LOW', 'Low'), ('MEDIUM', 'Medium'), ('HIGH', 'High')], help_text='Priority level of the case', max_length=10),
        ),
        migrations.AlterField(
            model_name='case',
            name='status',
            field=models.CharField(choices=[('OPEN', 'Open'), ('IN_PROGRESS', 'In Progress'), ('CLOSED', 'Closed')], default='OPEN', help_text='Current status of the case', max_length=20),
        ),
        migrations.AlterField(
            model_name='case',
            name='title',
            field=models.CharField(help_text='Short descriptive title for the case', max_length=200),
        ),
        migrations.AlterField(
            model_name='casemember',
            name='case',
            field=models.ForeignKey(help_text='Case this investigator is assigned to', on_delete=django.db.models.deletion.CASCADE, related_name='members', to='cases.case'),
        ),
        migrations.AlterField(
            model_name='casemember',
            name='user',
            field=models.ForeignKey(help_text='Investigator assigned to this case', on_delete=django.db.models.deletion.CASCADE, related_name='case_memberships', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterUniqueTogether(
            name='casemember',
            unique_together={('case', 'user')},
        ),
    ]
