# Generated by Django 6.0.2 on 2026-03-05 13:04

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('evidence', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='EvidenceNote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField(help_text='Observation or comment text')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='evidence_notes', to=settings.AUTH_USER_MODEL)),
                ('evidence', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notes', to='evidence.evidence')),
            ],
            options={
                'verbose_name': 'Evidence Note',
                'verbose_name_plural': 'Evidence Notes',
                'ordering': ['created_at'],
            },
        ),
    ]
