# Generated by Django 6.0.2 on 2026-03-05 16:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('evidence', '0002_evidencenote'),
    ]

    operations = [
        migrations.AddField(
            model_name='evidence',
            name='description',
            field=models.TextField(blank=True, default='', help_text='Brief description of the evidence'),
        ),
    ]
